### ISSUE TITLE
change from sis id to canvas id

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/quiz-extension#9]
use the student's canvas id (not sis id) to create csvs and to push back update

**Comment by alisonmyers** [comment]
will allow us to use canvasapi get_users() (plus, I don't think all access allows seeing sis)

**Comment by JeremyH011** [comment]
Hi Alison, the script already uses canvas student id to push back update. I only included SIS ID in the csv download so it differentiates people who have the same name (e.g. there could be 2 of 'Eric Chan' in the same course) since you wouldn't be able to tell between them without the SIS id.

Or is this is a rare occurrence and it probably wouldn't matter?

**Comment by alisonmyers** [comment]
the canvas user id should be unique, in the same way the sis id is

**Comment by JeremyH011** [comment]
I am aware of that, I'm just asking if a teacher has to edit the file, they won't have a list of canvas IDs on hand, they will have a list of student IDs and names. In a class, where we have two students with the same name (in this example, Eric Chan), how does a professor connect a student to their canvas ID without a corresponding SIS ID?

**Comment by alisonmyers** [comment]
The student ids should come from the create student list function that I suggested - this should have their name and canvas id

**Comment by alisonmyers** [comment]
ohhh wait I see what you mean... yes, okay, keep the sis id!
